# Generated by Django 4.0 on 2022-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
