# Generated by Django 4.0 on 2022-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDjangoForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('ContactNumber', models.IntegerField(max_length=100)),
                ('Emailid', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Confirm_Emailid', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Python', models.CharField(max_length=100)),
                ('Java', models.CharField(max_length=100)),
            ],
        ),
    ]
