# Generated by Django 4.0 on 2022-02-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdjangoforms',
            name='ContactNumber',
            field=models.IntegerField(),
        ),
    ]
