# Generated by Django 4.0 on 2022-02-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Bigdata',
            new_name='bigdata',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Contact_Number',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Courseintrested',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email_id',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='First_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='User_name',
        ),
    ]
