# Generated by Django 4.0 on 2022-02-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0002_rename_bigdata_student_bigdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Django',
            new_name='django',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Java',
            new_name='java',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='State',
            new_name='state',
        ),
    ]
