# Generated by Django 4.0 on 2022-02-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0003_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
