# Generated by Django 4.0 on 2022-02-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0004_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
