# Generated by Django 4.0 on 2022-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0006_student_confomepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
