# Generated by Django 4.0 on 2022-07-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messages',
        ),
    ]
