# Generated by Django 4.0 on 2022-07-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0008_rename_message_contact_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
